
{{- if and .Values.crossplane_providerconfig.aws.enabled .Values.cloud.aws.services.mysql.enabled -}}
apiVersion: rds.aws.upbound.io/v1beta1
kind: Instance
metadata:
  name: {{ .Values.global.app.name }}-aws-mysql
  namespace: {{ .Release.Namespace }}
spec:
  forProvider:
    allocatedStorage: {{ .Values.cloud.aws.services.mysql.storage }}
    autoGeneratePassword: true
    autoMinorVersionUpgrade: true
    backupRetentionPeriod: {{ .Values.cloud.aws.services.mysql.backup_days }}
    backupWindow: 09:46-10:16
    dbName: {{ .Values.cloud.aws.services.mysql.database }}
    engine: mysql
    engineVersion: {{ .Values.cloud.aws.services.mysql.version }}
    instanceClass: {{ .Values.cloud.aws.services.mysql.instance }}
    maintenanceWindow: Mon:00:00-Mon:03:00
    passwordSecretRef:
      key: password
      name: {{ .Values.global.app.name }}-aws-mysql
      namespace: {{ .Release.Namespace }}
    publiclyAccessible: true
    region: {{ .Values.cloud.aws.region }}
    skipFinalSnapshot: true
    storageEncrypted: true
    storageType: gp2
    username: {{ .Values.cloud.aws.services.mysql.username }}
  writeConnectionSecretToRef:
    name: {{ .Values.global.app.name }}-aws-mysql-conn
    namespace: {{ .Release.Namespace }}
  providerConfigRef:
    name: {{ lower $.Values.crossplane_providerconfig.aws.aws_access_key_id }}-aws-creds
{{- end }}