
{{- if and .Values.crossplane_providerconfig.aws.enabled .Values.cloud.aws.services.postgre.enabled -}}
apiVersion: rds.aws.upbound.io/v1beta2
kind: Instance
metadata:
  name: {{ .Values.global.app.name }}-aws-postgre
  namespace: {{ .Release.Namespace }}
spec:
  forProvider:
    allocatedStorage: {{ .Values.cloud.aws.services.postgre.storage }}
    autoGeneratePassword: true
    autoMinorVersionUpgrade: true
    backupRetentionPeriod: {{ .Values.cloud.aws.services.postgre.backup_days }}
    backupWindow: 09:46-10:16
    dbName: {{ .Values.cloud.aws.services.postgre.database }}
    engine: postgres
    engineVersion: {{ .Values.cloud.aws.services.postgre.version | quote }}
    identifier: {{ .Values.global.app.name }}-aws-postgre
    instanceClass: {{ .Values.cloud.aws.services.postgre.instance }}
    maintenanceWindow: Mon:00:00-Mon:03:00
    passwordSecretRef:
      key: password
      name: {{ .Values.global.app.name }}-aws-postgre
      namespace: {{ .Release.Namespace }}
    publiclyAccessible: true
    region: {{ .Values.cloud.aws.region }}
    skipFinalSnapshot: true
    storageEncrypted: true
    storageType: gp2
    username: {{ .Values.cloud.aws.services.postgre.username }}
    dbSubnetGroupNameRef:
      name: {{ .Values.global.app.name }}-aws-db-subnetgroup
  writeConnectionSecretToRef:
    name: {{ .Values.global.app.name }}-aws-postgre-conn
    namespace: {{ .Release.Namespace }}
  providerConfigRef:
    name: {{ lower $.Values.crossplane_providerconfig.aws.aws_access_key_id }}-aws-creds
{{- end }}