{{- if and .Values.crossplane_providerconfig.aws.enabled .Values.cloud.aws.services.apps.fluent_bit.enabled -}}

apiVersion: helm.crossplane.io/v1beta1
kind: Release
metadata:
  name: {{ .Values.global.app.name }}-fluent-bit
  namespace: {{ .Release.Namespace }}
  labels:
    appName: {{ .Values.global.app.name }}
spec:
  forProvider:
    chart:
      name: fluent-bit
      repository: "oci://registry-1.docker.io/bitnamicharts"
      version: {{ .Values.cloud.aws.services.apps.fluent_bit.version }}
    namespace: fluent-bit
    values:
      config:
        inputs: {{ quote .Values.cloud.aws.services.apps.fluent_bit.inputs }}
        filters: {{ quote .Values.cloud.aws.services.apps.fluent_bit.filters }}
        outputs: {{ quote .Values.cloud.aws.services.apps.fluent_bit.outputs }}
        customParsers: {{ quote .Values.cloud.aws.services.apps.fluent_bit.customParsers }}
  providerConfigRef:
    name: {{ .Values.global.app.name }}-eks-helm

{{- end }}
---
{{- if and .Values.crossplane_providerconfig.aws.enabled .Values.cloud.aws.services.apps.fluent_bit.enabled }}
apiVersion: iam.aws.upbound.io/v1beta1
kind: Role
metadata:
  name: {{ .Values.global.app.name }}-fluentbit-role
  namespace: {{ .Release.Namespace }}
  labels:
    appName: {{ .Values.global.app.name }}
spec:
  forProvider:
    assumeRolePolicy: |
      {
        "Version": "2012-10-17",
        "Statement": [
          {
            "Effect": "Allow",
            "Principal": {
              "Service": "eks.amazonaws.com"
            },
            "Action": "sts:AssumeRole"
          }
        ]
      }
    tags:
      Name: {{ .Values.global.app.name }}-fluentbit-role
  providerConfigRef:
    name: {{ lower .Values.crossplane_providerconfig.aws.aws_access_key_id }}-aws-creds
{{- end }}
---
{{- if and .Values.crossplane_providerconfig.aws.enabled .Values.cloud.aws.services.apps.fluent_bit.enabled }}
apiVersion: iam.aws.upbound.io/v1beta1
kind: Policy
metadata:
  name: {{ .Values.global.app.name }}-fluentbit-policy
  namespace: {{ .Release.Namespace }}
  labels:
    appName: {{ .Values.global.app.name }}
spec:
  forProvider:
    policy: |
      {
        "Version": "2012-10-17",
        "Statement": [
          {
            "Sid": "fluentbitperm",
            "Effect": "Allow",
            "Action": [
              "logs:PutLogEvents",
              "logs:CreateLogStream",
              "logs:CreateLogGroup",
              "logs:DescribeLogStreams",
              "logs:DescribeLogGroups",
              "logs:FilterLogEvents"
            ],
            "Resource": [
              "*"
            ]
          }
        ]
      }
  providerConfigRef:
    name: {{ lower .Values.crossplane_providerconfig.aws.aws_access_key_id }}-aws-creds
{{- end }}
---
{{- if and .Values.crossplane_providerconfig.aws.enabled .Values.cloud.aws.services.apps.fluent_bit.enabled }}
apiVersion: iam.aws.upbound.io/v1beta1
kind: RolePolicyAttachment
metadata:
  name: {{ .Values.global.app.name }}-fluentbit-policy-attachment
  namespace: {{ .Release.Namespace }}
  labels:
    appName: {{ .Values.global.app.name }}
spec:
  forProvider:
    policyArn: arn:aws:iam::{{ .Values.cloud.aws.services.apps.fluent_bit.account_id }}:policy/{{ .Values.global.app.name }}-fluentbit-policy
    roleRef:
      name: {{ .Values.global.app.name }}-fluentbit-role
  providerConfigRef:
    name: {{ lower .Values.crossplane_providerconfig.aws.aws_access_key_id }}-aws-creds
{{- end }}
---
{{- if .Values.cloud.aws.services.apps.fluent_bit.enabled -}}
apiVersion: kubernetes.crossplane.io/v1alpha2
kind: Object
metadata:
  name: {{ .Values.global.app.name }}-fluent-bit-sa
spec:
  forProvider:
    manifest:
      apiVersion: v1
      kind: ServiceAccount
      metadata:
        annotations:
          eks.amazonaws.com/role-arn: arn:aws:iam::{{ .Values.cloud.aws.services.apps.fluent_bit.account_id }}:role/{{ .Values.global.app.name }}-fluentbit-role
        name: fluent-bit-sa
        namespace: fluent-bit
  providerConfigRef:
    name: {{ .Values.global.app.name }}-eks-kubernetes
{{- end }}
