global:
  app:
    name: providerconfig
    version: 1.0.0

crossplane_providerconfig:
  aws:
    enabled: false
    aws_access_key_id: 
    aws_secret_access_key: 
  azure:
    enabled: true
    clientId: 
    clientSecret:
    subscriptionId: 
    tenantId: 
    activeDirectoryEndpointUrl: "https://login.microsoftonline.com"
    resourceManagerEndpointUrl: "https://management.azure.com/"
    activeDirectoryGraphResourceId: "https://graph.windows.net/"
    sqlManagementEndpointUrl: "https://management.core.windows.net:8443/"
    galleryEndpointUrl: "https://gallery.azure.com/"
    managementEndpointUrl: "https://management.core.windows.net/"
